server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:33306/dev_concert
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL 실행하지 않음
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: Asia/Seoul
        connection.characterEncoding: UTF-8
        connection.useUnicode: true
        connection.collation: utf8mb4_unicode_ci
        format_sql: true  # SQL 보기 좋게 출력
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug                # SQL
    org.hibernate.orm.jdbc.bind: trace      # ← 바인드 파라미터 값
    org.hibernate.orm.jdbc.extract: off   # (선택) 결과 추출 로깅